### ISSUE TITLE
Installation never completed

### ISSUE THREAD

**Issue by y-nk** [corbinlc/GNURootDebian#199] opened 2017-08-06 22:26 UTC
Hi,

I'm trying to use this app on a pixel c running latest beta android O.
Unfortunately I cannot go further than the "installation in progress" toast message.

Is there a way to help debugging this ?

**Comment by girlich** [comment] 2017-08-22 05:45
The problem occurs also with the final release of Android 8.0.0.
I had it running on Android 7.1.2 before and yesterday I did the update to Android 8.0.0 and now its not working any more. Re-installing did only lead to this problem. It looks like something is starting up and then it crashes.

**Comment by AdamMatthewLTM** [comment] 2018-05-11 01:40
Hi all,

I am currently assisting the developers in sorting relevant issues for GNURoot Debian on GitHub. If the issue discussed is still relevant, could you please reply to this thread and state the issue needs to be resolved and I will attempt to sort it for you ASAP. If the issue is no longer relevant, please reply to this thread and state it has been resolved, and I will suggest this thread be closed.

Furthermore, if a particular issue is considered to be high priority, please state that you are requesting it to be considered as high priority and I will mark it as such.

Thank you all so much for your time and understanding,
-Adam

**Comment by girlich** [comment] 2018-05-11 09:00
This issue is still very relevant but the problem was mostly discussed in the issue #206. So to simplify things you can close this issure here with "duplicate to #206".

**Comment by AdamMatthewLTM** [comment] 2018-05-21 04:42
Hi all,

My apologies for the delay, and thank you for the reply @girlich . As you stated, this is a duplicate of issue #206 (which I have marked already as highest priority to resolve), therefore I am recommending this thread be closed.

Thank you for your patience,
-Adam

**Closed** 2018-06-20 01:33 UTC
