### ISSUE TITLE
Nexus 7 GNURoot "Unfortunately, GNURoot Debian has stopped."

### ISSUE THREAD

**Issue by SeaDude** [corbinlc/GNURootDebian#159] opened 2017-03-25 15:25 UTC
Hello, 

I don't have Google Play on my Nexus 7. Headed to this repo and downloaded GnuRootDebian.apk. Installed it on the Nexus 7. After clicking install, GNURootDebian says "GNURoot not yet installed. This could take a bit. Please wait.", then "Unfortunately, GNURoot Debian has stopped". 

Tried with both the armel and armhf builds, no go. 

- Am I missing something? 

- Is the .apk mentioned above a complete install package or just the GNURoot portion of a larger build? 

- Is there somewhere to download the installable .apk besides Google Play?

How about an FDroid build!

Thanks

**Comment by Root-voidX** [comment] 2017-04-01 03:56
I have a nexus 7 2012 with the latest play store beta build so its working fine. Can you do the following, clear cache, use a file explorer and delete the gnuroot debian folder on the device and then redownload from the play store ?

**Comment by SeaDude** [comment] 2017-04-02 04:45
I don't have Play Store on the device. I use FDROID. Would like to install GnuROOT without the Play Store. Is it possible?

**Comment by Root-voidX** [comment] 2017-04-03 01:51
Yes I believe corbinlc has uploaded a apk. I am on the beta version so I doubt you can get that. Try apk mirror. Or the main github page might have a link

**Comment by SeaDude** [comment] 2017-04-05 03:16
Please see the initial post! I tried the .apk on this Github site. Installing it prompted the initial post and error messages.

**Comment by SeaDude** [comment] 2017-04-09 14:54
Anyone? 

- I do not have nor want Google Play on my device (Nexus 7 WiFi + Cell)
- Its rooted
- I installed the .apk from the Github site
- Received the "Unfortunately..." error
- Tried clearing and reinstalling, same issue

Please help. 
Thanks

**Comment by Root-voidX** [comment] 2017-04-09 16:35
I do not know if google play services is required. But have you tried to find it on apkmirror?

**Comment by SeaDude** [comment] 2017-04-11 03:49
No. That site has too many trackers to trust. I'd prefer to learn how to install it from the .apk on this github repor or why i'm getting the described error directly from the dev.

**Comment by corbinlc** [comment] 2017-04-11 17:36
You need an .obb file put in the correct place (it is a Play Store extension file and is not part of the .apk file).  An install from the play store both installs the .apk files as usual, https://github.com/corbinlc/GNURootDebian/tree/master/GNURootDebianSource (you want the armhf version) and a .obb file if one is needed.  Before you launch the app, you need to download the .obb file (https://github.com/corbinlc/GNURootDebian/tree/master/GNURootDebianSource/src/armhf/obb) and put it in the correct place.  The correct place is normally something like /sdcard/Android/obb/com.gnuroot.debian/main.10.com.gnuroot.debian.obb .  You should already see the /sdcard/Android directories, but you may need to create the obb/com.gnuroot.debian directories.

Tell me if this works for you.

**Comment by SeaDude** [comment] 2017-04-15 17:03
This is great information. Thank you Corbin. 

Is the .obb install directory the same if I install GNURootDebianSource-armhf-release.apk as a system app to the path `/data/app`?

**Comment by SeaDude** [comment] 2017-04-15 17:11
EH! Same error. 
Steps so far:
- Removed GNURoot entries in `packages.xml` and `packages.list`
- Installed `GNURootDebianSource-armhf-release.apk` to `/data/app`
- Installed `main.10.com.gnuroot.debian.obb` to `/sdcard/Android/src/armhf/obb`
- Rebooted device
- Click GNURootWheezy icon
- "GNURoot... not yet installed. This may take a minute."
- "Unfortunately, GNURoot Debian has stopped."

Maybe GRD can't be installed to `/data/app`?

**Comment by SeaDude** [comment] 2017-04-15 17:33
Bingo!. Appears to be working now!

- Removed GNURoot entries in packages.xml and packages.list (again just to be safe)
- Removed previously installed .apk
- adb reboot
- adb push GNURootDebianSource-armhf-release.apk to `/sdcard/Android/data`
- adb push main.10.com.gnuroot.debian.obb to `/sdcard/Android/src/armhf/obb`
- adb reboot
- Click GNURootWheezy icon
- Installation started
- Teradyne ascii art (success)

**Comment by SeaDude** [comment] 2017-04-15 17:33
Thank you for the help!

**Comment by stefanbaur** [comment] 2017-05-18 13:42
Hi, 

I'm having the same issue - GNURoot Debian Force-Closing straight after starting it and displaying the download message for a second - however, I'm having the issue with the official package installed from Google Play as well as if I transfer the APK from a Google-Play-enabled device to a device that isn't hooked up to Google Play.

Device with Google Play:
Motorola Milestone 2 (European version of "Droid 2") - Android Version 2.3.4 with Motoblur (stock install, no root)

Device without Google Play:
Motorola Droid 4 (XT894), rooted, Android-Version 6.0.1, CyanogenMod 13.0-20160418-SNAPSHOT-ZNH0EAO2NI-maserati

Both devices are equipped with a 32GB microSD card, so space should not be an issue.

GNURoot Debian Version, as reported by Google Play: 0.6.12_armhf

How can I get GNURoot Debian to run on at least one of those devices?

Kind Regards,
Stefan Baur

**Comment by stefanbaur** [comment] 2017-05-18 14:48
I tried the procedure suggested by SeaDude on April 15 on the above-mentioned Droid 4, sadly, it did not help either. No change in behavior.

**Comment by AdamMatthewLTM** [comment] 2018-05-11 01:31
Hi all,

I am currently assisting the developers in sorting relevant issues for GNURoot Debian on GitHub. If the issue discussed is still relevant, could you please reply to this thread and state the issue needs to be resolved and I will attempt to sort it for you ASAP. If the issue is no longer relevant, please reply to this thread and state it has been resolved, and I will suggest this thread be closed.

Furthermore, if a particular issue is considered to be high priority, please state that you are requesting it to be considered as high priority and I will mark it as such.

Thank you all so much for your time and understanding,
-Adam

**Closed** 2018-05-12 07:38 UTC

**Comment by Shuoen1997** [comment] 2018-07-26 21:23
OMG!! Thank you so much for this thread!! I was stuck on this for DAYS and this has saved me!

**Comment by SeaDude** [comment] 2018-07-27 04:56
Nice! Its cool to see it going to good use! "There be days of energy bottled up in those bullet points. Arrhg."
