### ISSUE TITLE
Nov 30th patch wipes p-root and forces reinstall?

### ISSUE THREAD

**Issue by Root-voidX** [corbinlc/GNURootDebian#129] opened 2016-12-05 21:23 UTC
Hey Corbin as per your request on issue #121.

I would like to submit an issue which arises with the Nov 30th patch. After updating gnuroot wipes the p-root and all packages. It forces a reinstall of p-root/chroot through the app and also forces octave to reinstall. It delete all previous packages so I was forced to reinstall DE and other packages. The new update doesn't do this for me but It may for some other people. So as per your request I opened the issue!

**Comment by corbinlc** [comment] 2016-12-05 23:35
How long have you been using GNURoot Debian?  I think I found the issue, but it would only impact users who have been using GNURoot Debian for a while.

**Comment by Root-voidX** [comment] 2016-12-06 00:02
I started using it since I would say end of July 2016. 

Does the new update fix this issue? The new update was quick did not require reinstall at all.

**Comment by corbinlc** [comment] 2016-12-06 00:07
The new update "should" fix this issue.  But, only if the issue is what I think it is.  I think I am right, but there is a chance there is another issue lurking.

**Comment by corbinlc** [comment] 2016-12-06 00:09
July 2016 isn't too long ago.  I will have to look at the code history to see if this problem could/should happen to someone who started in that time frame.

**Comment by corbinlc** [comment] 2016-12-06 00:19
Sure you don't mean July 2015?  If so, that makes a lot of sense with what I see, but July 2016 is too recent to have the issue I thought was causing this.

**Comment by Root-voidX** [comment] 2016-12-06 00:25
I started using it in 2016! I started using it when I got my note 7! As the Nov 30 was the first patch I ever gotten from the app. I may have used it back then but it wasn't installed on my s7e (replaced my note 7).

**Comment by corbinlc** [comment] 2016-12-06 00:26
Shoot.  I guess there must be another potential issue.  Back to brainstorming.

**Comment by Root-voidX** [comment] 2016-12-06 00:31
The Nov 30 update did this both on my s7e non rooted and my nexus 7 (2012) routed with cyanogenmod 14.1. 

It does seem the recent updates today fixed the issue, could it be that was the case because of the duplicated application from the Nov 30th update. Maybe it assumed it wasnt installed and did a fresh install overriding previous chroot?

**Comment by corbinlc** [comment] 2016-12-06 18:34
I loaded the "bad" release on my device after installing the release previous to it and it didn't reinstall everything.  I will try a couple of more devices and try doing more with the previous version before switching to the "bad" release.  Not sure.

**Comment by Root-voidX** [comment] 2016-12-06 18:54
So when you updated to the "bad" release it didn't say gnuroot not set up, setting up and started installing ?

That's what happened to me ?

**Comment by corbinlc** [comment] 2016-12-06 19:23
Correct.  It does not do that to me.  I am probably too late to save anyone hassle at this point, but I still hope to get to the bottom of this.

**Comment by Root-voidX** [comment] 2016-12-06 23:55
Of course so far no app crashes yet and all libraries work when called. Maybe whatever you fixed with the recent patch helped with that.

Accept for some questions regarding arm64 packages and for some reason xserver xsdl not working are the issues. I'm surprised how well arm linux works with programs that even scale to supercomputers =D

**Comment by corbinlc** [comment] 2016-12-09 20:48
I guess I will close this if after a while no one is reporting the same issue.  I am not sure what else I can fix for that bad release.  Time to move forward with new features.  Really sorry this happened.

**Comment by Root-voidX** [comment] 2016-12-09 21:21
Of course man. So far none of your updates after the Nov 30 patch did this. So it seems like it is fixed. If any future patch does this than I'll let you know. Otherwise you can close this issue whenever you want!

**Closed** 2017-01-31 20:37 UTC
