### ISSUE TITLE
hard links broken when running on Android Marshmallow?

### ISSUE THREAD

**Issue by drdynamics** [corbinlc/GNURootDebian#35] opened 2015-10-19 20:26 UTC
There's an issue with apt-get in GNURootDebian when running on Android Marshmallow.  It appears to be caused by an inability to set hard links.

**Comment by toniokroeger** [comment] 2015-10-22 07:58
I have the same issue on Android 6. apt-get is unable to create '/var/lib/dpkg/status-old', for example. Several other files can not be created in the installation process.

**Comment by corbinlc** [comment] 2015-10-22 17:07
Thanks!  I think I have a workaround for this working already.  I don't have a device running 6.0, but I have seen this problem once before on an earlier version of android.  I fixed it then, via a PRoot extension, but I the fix caused crashes on android 5.0/5.1.  I now have a new version of PRoot that has the extension working and doesn't cause crashes on 5.0/5.1.  It should solve your issue once I integrate it into an APK.  Once I am ready, I will provide the two of you with a test APK to work with.  If you confirm it works and I complete some testing with it, I will release it for all.

**Comment by corbinlc** [comment] 2015-10-22 18:59
I flashed marshmallow onto one of my devices.  I can reproduce the error.  I need to check the fix and then make sure it doesn't break existing users and then i can release.  Since I can reproduce, I shouldn't have to bother you.

**Comment by corbinlc** [comment] 2015-10-22 19:21
Yup.  Bringing the link2symlink PRoot extension back to life solves this.  Now onto the less fun task of trying it on multiple devices and making sure it doesn't break someone upgrading (and if so, make the upgrade only happen if needed).

**Comment by drdynamics** [comment] 2015-10-22 19:47
Hi Corbin,

This sounds like tentatively good news. I'm sure that there are all kinds
of wrinkles when you have multiple releases of Android to support, and it's
not like they give you any warning that, oh by the way, we're changing x,
y, or z when we release version n+1. Anyway, I really appreciate the
updates, and I'm looking forward to trying it out.

BTW, the reason that I discovered this in the first place is that I was
trying to work around Debian's packages for octave add-ons, especially
octave-control, and instead use octave's built in functionality of pulling
packages directly from octave-forge, and compiling in place. It looks like
I was successful on my other Android device (still on KitKat I think). Any
thoughts on this? It was slow enough to build octave-control that I just
left it overnight, so I don't actually know how long it took (galaxy note
10), but I think it works.

I think it's awesome that using this collection of open source tools, I can
actually get a better experience than using Matlab, which will only run
remotely when using Android. I think that the day that my phone plus
Chromecast and a Bluetooth keyboard and mouse replaces my laptop is maybe
not that far off.

Thanks again,

BM

**Comment by toniokroeger** [comment] 2015-10-23 08:34
Thanks a lot for your work!

**Comment by corbinlc** [comment] 2015-10-30 22:17
You should now be able to update to a version that has the link2symlink PRoot extension working.  I had a small glitch rolling it out (had to debug a failure in my x86 build of the app), but it is there now.  I am going to close this but please open separate issues for the other issues raised.

**Closed by corbinlc** 2015-10-30 22:17 UTC

**Comment by drdynamics** [comment] 2015-10-31 02:28
Hi Corbin,

It looks like that did the trick. Nice.

Thanks again,
BM
