### ISSUE TITLE
Android N: can't apt-get upgrade - broken symlinks

### ISSUE THREAD

**Issue by divVerent** [corbinlc/GNURootDebian#103] opened 2016-08-25 16:27 UTC
Steps:
- Take a fresh Android N install.
- Install GNURoot Debian from the Play Store.
- Click Install.
- Click Launch.
- apt-get update
- apt-get upgrade

```
dpkg: error processing archive /var/cache/apt/archives/base-files_8+deb8u5_armhf.deb (--unpack):
 symbolic link '/etc/os-release' size has changed from 26 to 21
```

Yes, deleting this link makes apt continue - but there seem to be hundreds of those links.

It looks like the issue is that something must have "normalized" these symlinks into relative links, thereby breaking dpkg.

**Comment by divVerent** [comment] 2016-08-25 16:46
This issue is Android N specific - repeating the same step on a device with M doesn't cause the bug.

**Comment by divVerent** [comment] 2016-08-25 19:33
Found out something: the issue is that dpkg assumes that a file's st_size matches the length of the string returned by readlink().

```
$ ln -snf a b
$ stat b
  File: ‘b’ -> ‘a’
  Size: 1         	Blocks: 0          IO Block: 4096   symbolic link
```

On this Android N device, this isn't the case:

```
root@localhost:~# ln -snf a b
root@localhost:~# stat b
  File: 'b' -> 'a'
  Size: 18         	Blocks: 8          IO Block: 4096   symbolic link
```

Might have to do with file-based encryption being enabled on this Android N device - however, regular files (non-symlinks) don't exhibit this behavior. Can this maybe be fixed somewhere in PRoot, then?

**Comment by MatthewTighe** [comment] 2016-09-01 21:47
I'm having trouble recreating this bug on my nexus 6P (running N). What device are you using, and at which point during the upgrade process does the error appear?

Also make sure you're using the latest version of GNURoot Debian which was released on August 23rd, as that update included several changes to PRoot affecting links and symlinks.

**Comment by divVerent** [comment] 2016-09-02 00:24
I'll check that.

I am using a Pixel C, and I have switched it to file based encryption in
Developer Settings (involves a factory reset) to get the feature that it
can partially boot without first unlock. It's likely that this caused it
then (and messed up stat()).

And I can still reproduce it with current updates and after patching (proot
shows as from Aug 27).

**Comment by divVerent** [comment] 2016-09-02 00:31
BTW, I seem to be able to reproduce this issue in plain androidterm:

dragon:/data/data/jackpal.androidterm/app_HOME $ ln -snf foo bar
dragon:/data/data/jackpal.androidterm/app_HOME $ stat bar
  File: 'bar' -> 'foo'
  Size: 18              Blocks: 8          IO Block: 4096   symbolic link
Device: b307h/45831d    Inode: 1204238     Links: 1
Access: (0777/lrwxrwxrwx)  Uid: (10104/ UNKNOWN)   Gid: (10104/ UNKNOWN)
Access: 2016-09-02 00:28:04.000000000
Modify: 2016-09-02 00:28:04.000000000
Change: 2016-09-02 00:28:04.000000000

Observe "Size: 18" which is plain incorrect and is exactly what breaks dpkg.

Still, given this seems like something PRoot is able to fix given where
it's sitting, I wonder if you could add this workaround (essentially,
whenever stat() returns that it's a symlink, call readlink() too then
update size). Does that sound feasible?

**Comment by guillemj** [comment] 2016-11-25 15:43
Hi! I was pointed to this issue by the Cydia developer Jay Freeman. I'd very much appreciate if someone here could report this to the Android developers, as this seems to be a regression, and it would be nice to get it fixed, as this goes against POSIX.

For dpkg 1.18.16 (which should happen in a couple of days at most) I'll probably relax the check and allow size differences that are shorter than expected, but still emit a warning. Hope this makes the current situation for now more bearable.

**Comment by fornwall** [comment] 2016-11-26 00:27
@guillemj I've reported the issue upstream at https://code.google.com/p/android/issues/detail?id=228651 where I referenced this issue.

A workaround in dpkg 1.18.16 would be great (users of Termux are also bitten by this bug)!

**Comment by fornwall** [comment] 2016-11-30 23:20
@guillemj Is it still the plan to have dpkg 1.18.6 out with the mentioned change shortly?

**Comment by corbinlc** [comment] 2016-12-01 19:34
I don't have a device running Android N.  @MatthewTighe is your device running Android N?  @divVerent we could probably do something in proot to correct this.  Can you call readlink on a link that you have created, so I can see what is being written instead of just "foo" in your example.   
readlink might return the right value since the link seems to print out correctly as in this:
File: 'bar' -> 'foo'
Size: 18 Blocks: 8 IO Block: 4096 symbolic link
Can you send me the symbolic link itself?  I want to look at it in a hex editor and see if there actually are extra characters written, or if it is just the size that is wrong.

**Comment by MatthewTighe** [comment] 2016-12-01 20:08
@corbinlc I am running Android N but the issue isn't repeatable on my device using the update currently on the play store.

**Comment by guillemj** [comment] 2016-12-04 04:52
@fornwall Yes, I'd like to get a release out later today. Otherwise tomorrow the latest.

**Comment by marlaw** [comment] 2016-12-08 21:46
Android 7.1, Pixel, last version of software updates and version of GNURootDebian released on the 7th December still has the symbolic link issue" on that issue when i do apt-get upgrade (dpkg)

**Comment by corbinlc** [comment] 2016-12-08 22:54
To confirm, this happens on both the Pixel phone and the Pixel C tablet... correct?  I am probably going to buy one of them, but I want to make sure I don't get the wrong thing.  Leaning towards the phone, but orders are backed up on it.

**Comment by corbinlc** [comment] 2016-12-09 20:39
I added an extension that may fix this issue.  You can get it the testing version here:
https://play.google.com/apps/testing/com.gnuroot.debian
I just pushed it, so it may take a couple of hours to show up (normally happens pretty fast, but Google says it can take up to 2 hours).  The versionCode should be >= 55 and the versionName should be >= 0.6.5 .  Once you are certain you have the new testing version, can you give it a whirl and tell me what you see.

**Comment by marlaw** [comment] 2016-12-09 20:48
@corbinlc perhaps I just need to wait a bit or maybe there's a G+ community to be joined?

> App not available for this account

>Your account isn't currently eligible for this app's testing program.
>If you've been invited to become a tester, make sure that you're signed in to the account that was invited to the testing program. If you've been invited to a Google Group or Google+ Community as part of the program, make sure that you've joined the Group or Community.

**Comment by corbinlc** [comment] 2016-12-09 21:02
People used to join this community https://plus.google.com/u/0/communities/116211239514009477744 , but I just switched it to an open beta program, when I pushed this new beta version, so membership in that google+ community  shouldn't matter.  Since I just pushed that change, I would wait a couple of hours and see if it works for you then.

**Comment by marlaw** [comment] 2016-12-09 21:07
@corbinlc seems to work now! apt-get upgrade completes!

note: apt-get update didn't work the first time around, i had to reissue it but worked the second time. Then I did apt-get upgrade and that worked straight away.

the error was:

> E: Unable to determine file size for fd 11 - fstat (1: Operation not permitted)

Thanks!

**Comment by corbinlc** [comment] 2016-12-09 21:13
Glad the new extension worked.  I just made sure it didn't break people who weren't broken, but couldn't confirm it would help you all, as I don't yet have a pixel running Android N.  

The issue where it says something failed, normally fstat with a blank path (just -) is a known issue, but I don't know how yet to solve it.  It is something happening in proot, where the I think a path or a file handle is being corrupted randomly.  Each new build changes when and where this happens.  The frequency of an error is different per device.  Really annoying actually.  If anyone a short recipe which makes this occur even 1 in 10 times on my devices, then I should be able to debug further.

**Comment by corbinlc** [comment] 2016-12-09 21:14
Anyway, feel free to use this beta version as you see fit.  I have done too many updates this week.  I will wait until we get more testing done before pushing this out.

**Comment by marlaw** [comment] 2016-12-09 23:39
thanks! for what is worth i was messing with adding some stretch apt repo in sources and when i hit apt-get update the fd issue happened again. Second attempted worked.

**Comment by guillemj** [comment] 2016-12-17 01:51
Heya, sorry for the delay, I've just released dpkg 1.18.16 now with the workaround explained above. I didn't rush it earlier as I saw that this had already worked around in this distro anyway. :)

**Comment by corbinlc** [comment] 2016-12-21 06:49
I pushed a new beta release (make sure it says 0.6.7) out today.  Can people make sure this doesn't reintroduce any problem for you?  This is the first one I plan on pushing to the main release that has the workaround for Android reporting the size of symbolic links incorrectly.  The new change to 0.6.7 vs 0.6.6 is it should get rid of a PRoot issue that would show up randomly before and cause fstat calls to possibly fail.  The issue that @marlaw mentioned occurred while he was doing apt-get updates.

**Comment by corbinlc** [comment] 2016-12-21 17:10
Please someone confirm or reject that this (broken apt-get on Pixel devices) is still fixed in 0.6.7 (the newest beta release).  I want to push that version to everyone.

**Comment by marlaw** [comment] 2016-12-21 17:29
@corbinlc 0.6.7 works well (apt-get update and upgrade). No issues seen.

**Comment by corbinlc** [comment] 2016-12-21 20:40
Given the functionality of the new PRoot extension and the feedback received, I am going to say, we now get correct size from lstat calls on symbolic links and close this issue.  This solves the issue with the older versions of dpkg.  Please open a new issue for other things you want fixed.

**Closed by corbinlc** 2016-12-21 20:40 UTC
